#   [Lift Operator By SOM] #

#Must Have FormAPI on Your server#
#Join FearMC best skyblock server 
# Subscribe to TECH_GAMING_SOM #
#Lift Warps 
iron-world: "Hypixel - Skyblock Hub"
iron-x: "-349"
iron-y: "100"
iron-z: "137"

gold-world: "Hypixel - Skyblock Hub"
gold-x: "-349"
gold-y: "100"
gold-z: "137"

lapis-world: "Hypixel - Skyblock Hub"
lapis-x: "-359"
lapis-y: "84"
lapis-z: "137"

redstone-world: "Hypixel - Skyblock Hub"
redstone-x: "-359"
redstone-y: "69"
redstone-z: "137"

emerald-world: "Hypixel - Skyblock Hub"
emerald-x: "-359"
emerald-y: "53"
emerald-z: "137"

diamond-world: "Hypixel - Skyblock Hub"
diamond-x: "-359"
diamond-y: "30"
diamond-z: "137"

obsidian-world: "Hypixel - Skyblock Hub"
obsidian-x: "-359"
obsidian-y: "14"
obsidian-z: "137"
